name: Daily Stock Report Bot

on:
  schedule:
    # UTC 시간 기준이야. 한국 시간(KST)보다 9시간 느려.
    # 한국 아침 6시에 돌리고 싶으면 전날 밤 9시(21시)로 설정해야 해.
    # 분 시간 일 월 요일
    - cron: '0 21 * * *'
  workflow_dispatch: # 개발할 때 수동으로 버튼 눌러서 테스트해 볼 수 있게 해주는 아주 유용한 옵션!

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

 steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 환경 세팅
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # 패키지 설치 속도를 빠르게 해줌

      - name: 필요 라이브러리 설치
        run: pip install -r requirements.txt

      - name: 뉴스 크롤링 & AI 리포트 생성 실행
        env:
          # 아까 Secrets에 저장한 키를 파이썬 스크립트로 넘겨줌
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
